/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Julianna Boado test
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        setTitle("Home Page");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        North_HomePage = new javax.swing.JPanel();
        HomePageBtn1 = new javax.swing.JButton();
        MoviesPageBtn1 = new javax.swing.JButton();
        ResPageBtn1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Center_HomePage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        North_HomePage.setBackground(new java.awt.Color(176, 52, 60));

        HomePageBtn1.setBackground(new java.awt.Color(176, 52, 60));
        HomePageBtn1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        HomePageBtn1.setForeground(new java.awt.Color(255, 255, 255));
        HomePageBtn1.setText("HOME");
        HomePageBtn1.setBorder(null);

        MoviesPageBtn1.setBackground(new java.awt.Color(176, 52, 60));
        MoviesPageBtn1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MoviesPageBtn1.setForeground(new java.awt.Color(255, 255, 255));
        MoviesPageBtn1.setText("MOVIES");
        MoviesPageBtn1.setBorder(null);

        ResPageBtn1.setBackground(new java.awt.Color(176, 52, 60));
        ResPageBtn1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ResPageBtn1.setForeground(new java.awt.Color(255, 255, 255));
        ResPageBtn1.setText("RESERVATION");
        ResPageBtn1.setBorder(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        javax.swing.GroupLayout North_HomePageLayout = new javax.swing.GroupLayout(North_HomePage);
        North_HomePage.setLayout(North_HomePageLayout);
        North_HomePageLayout.setHorizontalGroup(
            North_HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(North_HomePageLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 600, Short.MAX_VALUE)
                .addComponent(HomePageBtn1)
                .addGap(64, 64, 64)
                .addComponent(MoviesPageBtn1)
                .addGap(64, 64, 64)
                .addComponent(ResPageBtn1)
                .addGap(30, 30, 30))
        );
        North_HomePageLayout.setVerticalGroup(
            North_HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(North_HomePageLayout.createSequentialGroup()
                .addGroup(North_HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(North_HomePageLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(North_HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ResPageBtn1)
                            .addComponent(MoviesPageBtn1)
                            .addComponent(HomePageBtn1)))
                    .addGroup(North_HomePageLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(North_HomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        Center_HomePage.setBackground(new java.awt.Color(0, 0, 0));
        Center_HomePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 65)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Popcorns Ready, Are You?");
        Center_HomePage.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 990, -1));

        jButton1.setBackground(new java.awt.Color(176, 52, 60));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reserve Your Seat!");
        jButton1.setBorder(null);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Center_HomePage.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 250, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HomePage.png"))); // NOI18N
        Center_HomePage.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1180, -1));

        getContentPane().add(Center_HomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1200, 566));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MoviesPage Movies = new MoviesPage();
        Movies.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Center_HomePage;
    private javax.swing.JButton HomePageBtn1;
    private javax.swing.JButton MoviesPageBtn1;
    private javax.swing.JPanel North_HomePage;
    private javax.swing.JButton ResPageBtn1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
