/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author saman
 */
public class MoviesPage extends javax.swing.JFrame {

    /**
     * Creates new form Movies
     */
    public MoviesPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelFlowPoster = new javax.swing.JLabel();
        jLabelMoanaPoster = new javax.swing.JLabel();
        jLabelGorgePoster = new javax.swing.JLabel();
        jLabelFDeadThingPoster = new javax.swing.JLabel();
        jLabelCompanionPoster = new javax.swing.JLabel();
        jLabelCompleteUnknownPoster = new javax.swing.JLabel();
        jLabelFlow = new javax.swing.JLabel();
        Home5 = new javax.swing.JLabel();
        jButtonFlow = new javax.swing.JButton();
        Home6 = new javax.swing.JLabel();
        Home7 = new javax.swing.JLabel();
        jLabelGorge1 = new javax.swing.JLabel();
        jLabelGorge2 = new javax.swing.JLabel();
        jLabelDeadThing1 = new javax.swing.JLabel();
        jLabelDeadThing2 = new javax.swing.JLabel();
        jLabelMoana1 = new javax.swing.JLabel();
        jLabelMoana2 = new javax.swing.JLabel();
        Home13 = new javax.swing.JLabel();
        Home14 = new javax.swing.JLabel();
        jButtonGorge = new javax.swing.JButton();
        jButtonDeadThing = new javax.swing.JButton();
        Home15 = new javax.swing.JLabel();
        Home16 = new javax.swing.JLabel();
        Home17 = new javax.swing.JLabel();
        jButtonMoana = new javax.swing.JButton();
        Home18 = new javax.swing.JLabel();
        Home19 = new javax.swing.JLabel();
        jLabelTheCompanion1 = new javax.swing.JLabel();
        jLabelTheCompleteUnknown1 = new javax.swing.JLabel();
        jLabelTheCompleteUnknown2 = new javax.swing.JLabel();
        jLabelTheCompanion2 = new javax.swing.JLabel();
        jButtonCompanion = new javax.swing.JButton();
        jButtonCompleteUnknown = new javax.swing.JButton();
        Home24 = new javax.swing.JLabel();
        Home25 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jButtonHome = new javax.swing.JButton();
        jButtonReservation = new javax.swing.JButton();
        jButtonMovies = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setBackground(new java.awt.Color(175, 52, 59));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelFlowPoster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metrocine/flow.jpg"))); // NOI18N

        jLabelMoanaPoster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metrocine/moana.jpg"))); // NOI18N

        jLabelGorgePoster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metrocine/the gorge.jpg"))); // NOI18N

        jLabelFDeadThingPoster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metrocine/dead thing.jpg"))); // NOI18N

        jLabelCompanionPoster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metrocine/companion.jpg"))); // NOI18N

        jLabelCompleteUnknownPoster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metrocine/unknonw.jpg"))); // NOI18N

        jLabelFlow.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFlow.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelFlow.setForeground(new java.awt.Color(175, 52, 59));
        jLabelFlow.setText("FLOW");

        Home5.setBackground(new java.awt.Color(255, 255, 255));
        Home5.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Home5.setForeground(new java.awt.Color(153, 153, 153));
        Home5.setText("10:00AM 12:30PM ");

        jButtonFlow.setBackground(new java.awt.Color(242, 198, 112));
        jButtonFlow.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonFlow.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFlow.setText("GET TICKETS");
        jButtonFlow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlowActionPerformed(evt);
            }
        });

        Home6.setBackground(new java.awt.Color(255, 255, 255));
        Home6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Home6.setText("MARCH 12, 2025");

        Home7.setBackground(new java.awt.Color(255, 255, 255));
        Home7.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Home7.setForeground(new java.awt.Color(153, 153, 153));
        Home7.setText("3:00PM");

        jLabelGorge1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelGorge1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelGorge1.setForeground(new java.awt.Color(175, 52, 59));
        jLabelGorge1.setText("THE");

        jLabelGorge2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelGorge2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelGorge2.setForeground(new java.awt.Color(175, 52, 59));
        jLabelGorge2.setText("GORGE");

        jLabelDeadThing1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDeadThing1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelDeadThing1.setForeground(new java.awt.Color(175, 52, 59));
        jLabelDeadThing1.setText("THE DEAD");

        jLabelDeadThing2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDeadThing2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelDeadThing2.setForeground(new java.awt.Color(175, 52, 59));
        jLabelDeadThing2.setText("THING");

        jLabelMoana1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMoana1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelMoana1.setForeground(new java.awt.Color(175, 52, 59));
        jLabelMoana1.setText("MOANA");

        jLabelMoana2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMoana2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelMoana2.setForeground(new java.awt.Color(175, 52, 59));
        jLabelMoana2.setText("RETURNS");

        Home13.setBackground(new java.awt.Color(255, 255, 255));
        Home13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Home13.setText("MARCH 12, 2025");

        Home14.setBackground(new java.awt.Color(255, 255, 255));
        Home14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Home14.setText("MARCH 12, 2025");

        jButtonGorge.setBackground(new java.awt.Color(242, 198, 112));
        jButtonGorge.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonGorge.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGorge.setText("GET TICKETS");
        jButtonGorge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGorgeActionPerformed(evt);
            }
        });

        jButtonDeadThing.setBackground(new java.awt.Color(242, 198, 112));
        jButtonDeadThing.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonDeadThing.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDeadThing.setText("GET TICKETS");
        jButtonDeadThing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeadThingActionPerformed(evt);
            }
        });

        Home15.setBackground(new java.awt.Color(255, 255, 255));
        Home15.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Home15.setForeground(new java.awt.Color(153, 153, 153));
        Home15.setText("10:00AM 12:30PM ");

        Home16.setBackground(new java.awt.Color(255, 255, 255));
        Home16.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Home16.setForeground(new java.awt.Color(153, 153, 153));
        Home16.setText("10:00AM 12:30PM ");

        Home17.setBackground(new java.awt.Color(255, 255, 255));
        Home17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Home17.setText("MARCH 12, 2025");

        jButtonMoana.setBackground(new java.awt.Color(242, 198, 112));
        jButtonMoana.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonMoana.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMoana.setText("GET TICKETS");
        jButtonMoana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoanaActionPerformed(evt);
            }
        });

        Home18.setBackground(new java.awt.Color(255, 255, 255));
        Home18.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Home18.setForeground(new java.awt.Color(153, 153, 153));
        Home18.setText("10:00AM 12:30PM ");

        Home19.setBackground(new java.awt.Color(255, 255, 255));
        Home19.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Home19.setForeground(new java.awt.Color(153, 153, 153));
        Home19.setText("3:00PM");

        jLabelTheCompanion1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTheCompanion1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelTheCompanion1.setForeground(new java.awt.Color(175, 52, 59));
        jLabelTheCompanion1.setText("THE");

        jLabelTheCompleteUnknown1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTheCompleteUnknown1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelTheCompleteUnknown1.setForeground(new java.awt.Color(175, 52, 59));
        jLabelTheCompleteUnknown1.setText("THE COMPLETE");

        jLabelTheCompleteUnknown2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTheCompleteUnknown2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelTheCompleteUnknown2.setForeground(new java.awt.Color(175, 52, 59));
        jLabelTheCompleteUnknown2.setText("UNKOWN");

        jLabelTheCompanion2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTheCompanion2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelTheCompanion2.setForeground(new java.awt.Color(175, 52, 59));
        jLabelTheCompanion2.setText("COMPANION");

        jButtonCompanion.setBackground(new java.awt.Color(242, 198, 112));
        jButtonCompanion.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonCompanion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCompanion.setText("GET TICKETS");
        jButtonCompanion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompanionActionPerformed(evt);
            }
        });

        jButtonCompleteUnknown.setBackground(new java.awt.Color(242, 198, 112));
        jButtonCompleteUnknown.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonCompleteUnknown.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCompleteUnknown.setText("GET TICKETS");
        jButtonCompleteUnknown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompleteUnknownActionPerformed(evt);
            }
        });

        Home24.setBackground(new java.awt.Color(255, 255, 255));
        Home24.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Home24.setForeground(new java.awt.Color(153, 153, 153));
        Home24.setText("10:00AM 12:30PM ");

        Home25.setBackground(new java.awt.Color(255, 255, 255));
        Home25.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Home25.setForeground(new java.awt.Color(153, 153, 153));
        Home25.setText("10:00AM 12:30PM ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFlowPoster)
                    .addComponent(jLabelMoanaPoster))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Home19, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMoana1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelFlow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Home5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Home6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Home7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonFlow))
                            .addComponent(jLabelMoana2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Home17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMoana)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Home18, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCompanionPoster)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelTheCompanion1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelTheCompanion2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonCompanion))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(Home24, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelGorgePoster)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelGorge1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelGorge2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Home13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonGorge)
                                            .addComponent(Home15, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCompleteUnknownPoster)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTheCompleteUnknown1)
                                    .addComponent(jLabelTheCompleteUnknown2)
                                    .addComponent(jButtonCompleteUnknown)
                                    .addComponent(Home25, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelFDeadThingPoster)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelDeadThing1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelDeadThing2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonDeadThing)
                                            .addComponent(Home14, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Home16, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(7, 7, 7))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelFlowPoster)
                            .addComponent(jLabelGorgePoster, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelFDeadThingPoster, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabelFlow, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Home6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonFlow)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(Home5, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21))
                                    .addComponent(Home7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabelGorge1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGorge2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Home13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGorge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Home15, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabelDeadThing1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDeadThing2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Home14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeadThing)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Home16)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMoanaPoster)
                            .addComponent(jLabelCompanionPoster)
                            .addComponent(jLabelCompleteUnknownPoster)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(jLabelMoana1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelMoana2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(Home17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonMoana)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Home18, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabelTheCompanion1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelTheCompanion2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jButtonCompanion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Home24, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabelTheCompleteUnknown1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTheCompleteUnknown2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButtonCompleteUnknown)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Home25, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(Home19, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metrocine/metrocine logo.png"))); // NOI18N

        jButtonHome.setBackground(new java.awt.Color(175, 52, 59));
        jButtonHome.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonHome.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHome.setText("HOME");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonReservation.setBackground(new java.awt.Color(175, 52, 59));
        jButtonReservation.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonReservation.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReservation.setText("RESERVATION");
        jButtonReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservationActionPerformed(evt);
            }
        });

        jButtonMovies.setBackground(new java.awt.Color(175, 52, 59));
        jButtonMovies.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonMovies.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMovies.setText("MOVIES");
        jButtonMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoviesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMovies, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logo)
                        .addGap(12, 12, 12))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHome)
                            .addComponent(jButtonReservation)
                            .addComponent(jButtonMovies))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFlowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlowActionPerformed
       // Flow Button CLICK ME!
    }//GEN-LAST:event_jButtonFlowActionPerformed

    private void jButtonGorgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGorgeActionPerformed
         // The Gorge Button CLICK ME!
    }//GEN-LAST:event_jButtonGorgeActionPerformed

    private void jButtonDeadThingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeadThingActionPerformed
         // The Dead Thing Button CLICK ME!
    }//GEN-LAST:event_jButtonDeadThingActionPerformed

    private void jButtonMoanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoanaActionPerformed
         // Moana Returns Button CLICK ME!
    }//GEN-LAST:event_jButtonMoanaActionPerformed

    private void jButtonCompanionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompanionActionPerformed
         // Companion Button CLICK ME!
    }//GEN-LAST:event_jButtonCompanionActionPerformed

    private void jButtonCompleteUnknownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompleteUnknownActionPerformed
         // Complete Unknown Button CLICK ME!
    }//GEN-LAST:event_jButtonCompleteUnknownActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
       // home button
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservationActionPerformed
        // reservation button from menu
        ReservationPage Reservation = new ReservationPage();
        Reservation.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonReservationActionPerformed

    private void jButtonMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoviesActionPerformed
        // movie button from menu
        MoviesPage Movies = new MoviesPage();
        Movies.setVisible(true);
        this.dispose();    }//GEN-LAST:event_jButtonMoviesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoviesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoviesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoviesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoviesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoviesPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Home13;
    private javax.swing.JLabel Home14;
    private javax.swing.JLabel Home15;
    private javax.swing.JLabel Home16;
    private javax.swing.JLabel Home17;
    private javax.swing.JLabel Home18;
    private javax.swing.JLabel Home19;
    private javax.swing.JLabel Home24;
    private javax.swing.JLabel Home25;
    private javax.swing.JLabel Home5;
    private javax.swing.JLabel Home6;
    private javax.swing.JLabel Home7;
    private javax.swing.JButton jButtonCompanion;
    private javax.swing.JButton jButtonCompleteUnknown;
    private javax.swing.JButton jButtonDeadThing;
    private javax.swing.JButton jButtonFlow;
    private javax.swing.JButton jButtonGorge;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonMoana;
    private javax.swing.JButton jButtonMovies;
    private javax.swing.JButton jButtonReservation;
    private javax.swing.JLabel jLabelCompanionPoster;
    private javax.swing.JLabel jLabelCompleteUnknownPoster;
    private javax.swing.JLabel jLabelDeadThing1;
    private javax.swing.JLabel jLabelDeadThing2;
    private javax.swing.JLabel jLabelFDeadThingPoster;
    private javax.swing.JLabel jLabelFlow;
    private javax.swing.JLabel jLabelFlowPoster;
    private javax.swing.JLabel jLabelGorge1;
    private javax.swing.JLabel jLabelGorge2;
    private javax.swing.JLabel jLabelGorgePoster;
    private javax.swing.JLabel jLabelMoana1;
    private javax.swing.JLabel jLabelMoana2;
    private javax.swing.JLabel jLabelMoanaPoster;
    private javax.swing.JLabel jLabelTheCompanion1;
    private javax.swing.JLabel jLabelTheCompanion2;
    private javax.swing.JLabel jLabelTheCompleteUnknown1;
    private javax.swing.JLabel jLabelTheCompleteUnknown2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
