/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author saman
 */
public class ReservationPage extends javax.swing.JFrame {

    /**
     * Creates new form Reservation
     */
    public ReservationPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonHome = new javax.swing.JButton();
        jButtonReservation = new javax.swing.JButton();
        jButtonMovies = new javax.swing.JButton();
        North = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jButtonHome1 = new javax.swing.JButton();
        jButtonMovies1 = new javax.swing.JButton();
        jButtonReservation1 = new javax.swing.JButton();
        Center = new javax.swing.JPanel();
        jLabelTitleofMovie = new javax.swing.JLabel();
        choiceDate = new java.awt.Choice();
        jToggleButtonTime1 = new javax.swing.JToggleButton();
        jToggleButtonTime2 = new javax.swing.JToggleButton();
        jToggleButtonTime3 = new javax.swing.JToggleButton();
        jToggleButtonTime4 = new javax.swing.JToggleButton();
        panel3 = new java.awt.Panel();
        Home3 = new javax.swing.JLabel();
        Home6 = new javax.swing.JLabel();
        Home7 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        panel5 = new java.awt.Panel();
        Home8 = new javax.swing.JLabel();
        Home10 = new javax.swing.JLabel();
        jLabelTicketsTotal = new javax.swing.JLabel();
        Home13 = new javax.swing.JLabel();
        Home14 = new javax.swing.JLabel();
        jButtonMore = new javax.swing.JButton();
        jButtonLess = new javax.swing.JButton();
        Home15 = new javax.swing.JLabel();
        Home16 = new javax.swing.JLabel();
        panel4 = new java.awt.Panel();
        Home5 = new javax.swing.JLabel();
        jCheckBoxOgPopcorn = new javax.swing.JCheckBox();
        jCheckBoxChxPopcorn = new javax.swing.JCheckBox();
        jCheckBoxBBQPopcorn = new javax.swing.JCheckBox();
        jCheckBoxNachos = new javax.swing.JCheckBox();
        jCheckBoxSoda = new javax.swing.JCheckBox();
        jCheckBoxWater = new javax.swing.JCheckBox();
        Home11 = new javax.swing.JLabel();
        jTextFieldSnackTotal = new javax.swing.JTextField();
        panel6 = new java.awt.Panel();
        Home9 = new javax.swing.JLabel();
        jLabelTotalBill = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jButtonConfirm = new javax.swing.JButton();

        jButtonHome.setBackground(new java.awt.Color(175, 52, 59));
        jButtonHome.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonHome.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHome.setText("HOME");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonReservation.setBackground(new java.awt.Color(175, 52, 59));
        jButtonReservation.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonReservation.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReservation.setText("RESERVATION");
        jButtonReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservationActionPerformed(evt);
            }
        });

        jButtonMovies.setBackground(new java.awt.Color(175, 52, 59));
        jButtonMovies.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonMovies.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMovies.setText("MOVIES");
        jButtonMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoviesActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        North.setBackground(new java.awt.Color(175, 52, 59));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        jButtonHome1.setBackground(new java.awt.Color(175, 52, 59));
        jButtonHome1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonHome1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHome1.setText("HOME");
        jButtonHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHome1ActionPerformed(evt);
            }
        });

        jButtonMovies1.setBackground(new java.awt.Color(175, 52, 59));
        jButtonMovies1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonMovies1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMovies1.setText("MOVIES");
        jButtonMovies1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMovies1ActionPerformed(evt);
            }
        });

        jButtonReservation1.setBackground(new java.awt.Color(175, 52, 59));
        jButtonReservation1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonReservation1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReservation1.setText("RESERVATION");
        jButtonReservation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservation1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NorthLayout = new javax.swing.GroupLayout(North);
        North.setLayout(NorthLayout);
        NorthLayout.setHorizontalGroup(
            NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NorthLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(jButtonHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMovies1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonReservation1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        NorthLayout.setVerticalGroup(
            NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NorthLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMovies1)
                    .addComponent(jButtonReservation1)
                    .addComponent(jButtonHome1))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NorthLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(logo)
                .addContainerGap())
        );

        getContentPane().add(North, java.awt.BorderLayout.NORTH);

        Center.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitleofMovie.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitleofMovie.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabelTitleofMovie.setForeground(new java.awt.Color(175, 52, 59));
        jLabelTitleofMovie.setText("TITLE OF MOVIE");

        choiceDate.setBackground(new java.awt.Color(242, 198, 112));
        choiceDate.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        choiceDate.setForeground(new java.awt.Color(255, 255, 255));

        jToggleButtonTime1.setBackground(new java.awt.Color(242, 198, 112));
        jToggleButtonTime1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jToggleButtonTime1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButtonTime1.setText("10:00AM");
        jToggleButtonTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonTime1ActionPerformed(evt);
            }
        });

        jToggleButtonTime2.setBackground(new java.awt.Color(242, 198, 112));
        jToggleButtonTime2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jToggleButtonTime2.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButtonTime2.setText("12:30PM");
        jToggleButtonTime2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonTime2ActionPerformed(evt);
            }
        });

        jToggleButtonTime3.setBackground(new java.awt.Color(242, 198, 112));
        jToggleButtonTime3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jToggleButtonTime3.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButtonTime3.setText("3:00PM");
        jToggleButtonTime3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonTime3ActionPerformed(evt);
            }
        });

        jToggleButtonTime4.setBackground(new java.awt.Color(242, 198, 112));
        jToggleButtonTime4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jToggleButtonTime4.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButtonTime4.setText("6:00PM");
        jToggleButtonTime4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonTime4ActionPerformed(evt);
            }
        });

        panel3.setBackground(new java.awt.Color(175, 52, 59));
        panel3.setForeground(new java.awt.Color(175, 52, 59));

        Home3.setBackground(new java.awt.Color(255, 255, 255));
        Home3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Home3.setForeground(new java.awt.Color(242, 198, 112));
        Home3.setText("Personal Information");

        Home6.setBackground(new java.awt.Color(255, 255, 255));
        Home6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Home6.setForeground(new java.awt.Color(255, 255, 255));
        Home6.setText("Name:");

        Home7.setBackground(new java.awt.Color(255, 255, 255));
        Home7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Home7.setForeground(new java.awt.Color(255, 255, 255));
        Home7.setText("Email:");

        jTextFieldName.setBackground(new java.awt.Color(242, 198, 112));
        jTextFieldName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextFieldName.setForeground(new java.awt.Color(255, 255, 255));

        jTextFieldEmail.setBackground(new java.awt.Color(242, 198, 112));
        jTextFieldEmail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Home3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Home6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Home7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(jTextFieldEmail))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(Home3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Home6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Home7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        panel5.setBackground(new java.awt.Color(242, 198, 112));

        Home8.setBackground(new java.awt.Color(255, 255, 255));
        Home8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Home8.setForeground(new java.awt.Color(175, 52, 59));
        Home8.setText("Number of Tickers");

        Home10.setBackground(new java.awt.Color(255, 255, 255));
        Home10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Home10.setForeground(new java.awt.Color(255, 255, 255));
        Home10.setText("Cost:");

        jLabelTicketsTotal.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTicketsTotal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabelTicketsTotal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTicketsTotal.setText("440.00");

        Home13.setBackground(new java.awt.Color(255, 255, 255));
        Home13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Home13.setForeground(new java.awt.Color(255, 255, 255));
        Home13.setText("Quantity:");

        Home14.setBackground(new java.awt.Color(255, 255, 255));
        Home14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Home14.setForeground(new java.awt.Color(255, 255, 255));
        Home14.setText("Sub Total:");

        jButtonMore.setBackground(new java.awt.Color(175, 52, 59));
        jButtonMore.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMore.setForeground(new java.awt.Color(242, 198, 112));
        jButtonMore.setText("+");

        jButtonLess.setBackground(new java.awt.Color(175, 52, 59));
        jButtonLess.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLess.setForeground(new java.awt.Color(242, 198, 112));
        jButtonLess.setText("-");

        Home15.setBackground(new java.awt.Color(255, 255, 255));
        Home15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Home15.setForeground(new java.awt.Color(255, 255, 255));
        Home15.setText("440.00");

        Home16.setBackground(new java.awt.Color(255, 255, 255));
        Home16.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Home16.setForeground(new java.awt.Color(255, 255, 255));
        Home16.setText("1");

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addComponent(Home8, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel5Layout.createSequentialGroup()
                        .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Home10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Home15, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel5Layout.createSequentialGroup()
                                .addComponent(Home13, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(Home14, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                            .addGroup(panel5Layout.createSequentialGroup()
                                .addComponent(jButtonLess)
                                .addGap(18, 18, 18)
                                .addComponent(Home16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonMore)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelTicketsTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Home8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Home10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Home13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Home14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTicketsTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMore)
                    .addComponent(jButtonLess)
                    .addComponent(Home16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Home15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        panel4.setBackground(new java.awt.Color(175, 52, 59));
        panel4.setForeground(new java.awt.Color(175, 52, 59));

        Home5.setBackground(new java.awt.Color(255, 255, 255));
        Home5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Home5.setForeground(new java.awt.Color(242, 198, 112));
        Home5.setText("Snack Bar");

        jCheckBoxOgPopcorn.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jCheckBoxOgPopcorn.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxOgPopcorn.setText("Original Popcorn (P50.00)");
        jCheckBoxOgPopcorn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxOgPopcornActionPerformed(evt);
            }
        });

        jCheckBoxChxPopcorn.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jCheckBoxChxPopcorn.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxChxPopcorn.setText("Cheese Popcorn (P55.00)");
        jCheckBoxChxPopcorn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxChxPopcornActionPerformed(evt);
            }
        });

        jCheckBoxBBQPopcorn.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jCheckBoxBBQPopcorn.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxBBQPopcorn.setText("BBQ Popcorn (P55.00)");
        jCheckBoxBBQPopcorn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBBQPopcornActionPerformed(evt);
            }
        });

        jCheckBoxNachos.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jCheckBoxNachos.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxNachos.setText("Nachos (P60.00)");
        jCheckBoxNachos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNachosActionPerformed(evt);
            }
        });

        jCheckBoxSoda.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jCheckBoxSoda.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxSoda.setText("Soda (P30.00)");
        jCheckBoxSoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSodaActionPerformed(evt);
            }
        });

        jCheckBoxWater.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jCheckBoxWater.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxWater.setText("Water (P25.00)");
        jCheckBoxWater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxWaterActionPerformed(evt);
            }
        });

        Home11.setBackground(new java.awt.Color(255, 255, 255));
        Home11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Home11.setForeground(new java.awt.Color(255, 255, 255));
        Home11.setText("Sub Total:");

        jTextFieldSnackTotal.setBackground(new java.awt.Color(242, 198, 112));
        jTextFieldSnackTotal.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextFieldSnackTotal.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Home5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(jCheckBoxOgPopcorn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxNachos))
                    .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panel4Layout.createSequentialGroup()
                            .addComponent(jCheckBoxBBQPopcorn, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)
                            .addComponent(jCheckBoxWater, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel4Layout.createSequentialGroup()
                            .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Home11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBoxChxPopcorn))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jCheckBoxSoda, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addComponent(jTextFieldSnackTotal)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Home5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxOgPopcorn)
                    .addComponent(jCheckBoxNachos))
                .addGap(18, 18, 18)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxChxPopcorn)
                    .addComponent(jCheckBoxSoda))
                .addGap(18, 18, 18)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxBBQPopcorn)
                    .addComponent(jCheckBoxWater))
                .addGap(37, 37, 37)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Home11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSnackTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel6.setBackground(new java.awt.Color(242, 198, 112));

        Home9.setBackground(new java.awt.Color(255, 255, 255));
        Home9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Home9.setForeground(new java.awt.Color(175, 52, 59));
        Home9.setText("Total Bill");

        jLabelTotalBill.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTotalBill.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelTotalBill.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalBill.setText("00.00");

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Home9, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Home9)
                    .addComponent(jLabelTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonCancel.setBackground(new java.awt.Color(242, 198, 112));
        jButtonCancel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setText("CANCEL");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonConfirm.setBackground(new java.awt.Color(242, 198, 112));
        jButtonConfirm.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonConfirm.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConfirm.setText("CONFIRM");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CenterLayout = new javax.swing.GroupLayout(Center);
        Center.setLayout(CenterLayout);
        CenterLayout.setHorizontalGroup(
            CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTitleofMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CenterLayout.createSequentialGroup()
                        .addComponent(jToggleButtonTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonTime3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButtonTime4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(choiceDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CenterLayout.createSequentialGroup()
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        CenterLayout.setVerticalGroup(
            CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitleofMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CenterLayout.createSequentialGroup()
                        .addComponent(choiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButtonTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonTime3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonTime4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CenterLayout.createSequentialGroup()
                        .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        getContentPane().add(Center, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReservationActionPerformed

    private void jButtonMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoviesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMoviesActionPerformed

    private void jButtonHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHome1ActionPerformed

    private void jButtonReservation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservation1ActionPerformed
        // reservation button from menu
        ReservationPage Reservation = new ReservationPage();
        Reservation.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonReservation1ActionPerformed

    private void jButtonMovies1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMovies1ActionPerformed
        // movie button from menu
        MoviesPage Movies = new MoviesPage();
        Movies.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonMovies1ActionPerformed

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jCheckBoxWaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxWaterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxWaterActionPerformed

    private void jCheckBoxSodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSodaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSodaActionPerformed

    private void jCheckBoxNachosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNachosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxNachosActionPerformed

    private void jCheckBoxBBQPopcornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBBQPopcornActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxBBQPopcornActionPerformed

    private void jCheckBoxChxPopcornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxChxPopcornActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxChxPopcornActionPerformed

    private void jCheckBoxOgPopcornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxOgPopcornActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxOgPopcornActionPerformed

    private void jToggleButtonTime4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonTime4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonTime4ActionPerformed

    private void jToggleButtonTime3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonTime3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonTime3ActionPerformed

    private void jToggleButtonTime2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonTime2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonTime2ActionPerformed

    private void jToggleButtonTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonTime1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonTime1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Center;
    private javax.swing.JLabel Home10;
    private javax.swing.JLabel Home11;
    private javax.swing.JLabel Home13;
    private javax.swing.JLabel Home14;
    private javax.swing.JLabel Home15;
    private javax.swing.JLabel Home16;
    private javax.swing.JLabel Home3;
    private javax.swing.JLabel Home5;
    private javax.swing.JLabel Home6;
    private javax.swing.JLabel Home7;
    private javax.swing.JLabel Home8;
    private javax.swing.JLabel Home9;
    private javax.swing.JPanel North;
    private java.awt.Choice choiceDate;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonHome1;
    private javax.swing.JButton jButtonLess;
    private javax.swing.JButton jButtonMore;
    private javax.swing.JButton jButtonMovies;
    private javax.swing.JButton jButtonMovies1;
    private javax.swing.JButton jButtonReservation;
    private javax.swing.JButton jButtonReservation1;
    private javax.swing.JCheckBox jCheckBoxBBQPopcorn;
    private javax.swing.JCheckBox jCheckBoxChxPopcorn;
    private javax.swing.JCheckBox jCheckBoxNachos;
    private javax.swing.JCheckBox jCheckBoxOgPopcorn;
    private javax.swing.JCheckBox jCheckBoxSoda;
    private javax.swing.JCheckBox jCheckBoxWater;
    private javax.swing.JLabel jLabelTicketsTotal;
    private javax.swing.JLabel jLabelTitleofMovie;
    private javax.swing.JLabel jLabelTotalBill;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldSnackTotal;
    private javax.swing.JToggleButton jToggleButtonTime1;
    private javax.swing.JToggleButton jToggleButtonTime2;
    private javax.swing.JToggleButton jToggleButtonTime3;
    private javax.swing.JToggleButton jToggleButtonTime4;
    private javax.swing.JLabel logo;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    private java.awt.Panel panel6;
    // End of variables declaration//GEN-END:variables
}
