
import java.text.*;
import java.awt.event.*;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author saman
 */
public class ReservationPage extends javax.swing.JFrame {
    DecimalFormat df = new DecimalFormat("#.00");
    int ticketNum = 1;
    double ticketSubtotal;
    String timeSelected; 
    /**
     * Creates new form Reservation
     */
    public ReservationPage() {
        initComponents(); 
        setTitle("Ticket Reservation Page");
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonHome = new javax.swing.JButton();
        jButtonReservation = new javax.swing.JButton();
        jButtonMovies = new javax.swing.JButton();
        HourSelectBtnGroup = new javax.swing.ButtonGroup();
        North = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jButtonHome1 = new javax.swing.JButton();
        jButtonMovies1 = new javax.swing.JButton();
        jButtonReservation1 = new javax.swing.JButton();
        Center = new javax.swing.JPanel();
        jLabelTitleofMovie = new javax.swing.JLabel();
        Time10Button = new javax.swing.JToggleButton();
        Time12Button = new javax.swing.JToggleButton();
        Time3Button = new javax.swing.JToggleButton();
        Time6Button = new javax.swing.JToggleButton();
        panel3 = new java.awt.Panel();
        Home3 = new javax.swing.JLabel();
        Home6 = new javax.swing.JLabel();
        Home7 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        panel5 = new java.awt.Panel();
        Home8 = new javax.swing.JLabel();
        Home10 = new javax.swing.JLabel();
        jLabelTicketsTotal = new javax.swing.JLabel();
        Home13 = new javax.swing.JLabel();
        Home14 = new javax.swing.JLabel();
        jButtonMore = new javax.swing.JButton();
        jButtonLess = new javax.swing.JButton();
        Home15 = new javax.swing.JLabel();
        jLabelTicketQuantity = new javax.swing.JLabel();
        panel4 = new java.awt.Panel();
        Home5 = new javax.swing.JLabel();
        Home11 = new javax.swing.JLabel();
        jTextFieldSnackTotal = new javax.swing.JTextField();
        OGPopSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        CheePopSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BBQPopSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        NachoSpinner = new javax.swing.JSpinner();
        SodaSpinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        WaterSpinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        panel6 = new java.awt.Panel();
        Home9 = new javax.swing.JLabel();
        jLabelTotalBill = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jButtonConfirm = new javax.swing.JButton();
        MovieSelectComboBox = new javax.swing.JComboBox<>();

        jButtonHome.setBackground(new java.awt.Color(175, 52, 59));
        jButtonHome.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonHome.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHome.setText("HOME");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonReservation.setBackground(new java.awt.Color(175, 52, 59));
        jButtonReservation.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonReservation.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReservation.setText("RESERVATION");
        jButtonReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservationActionPerformed(evt);
            }
        });

        jButtonMovies.setBackground(new java.awt.Color(175, 52, 59));
        jButtonMovies.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonMovies.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMovies.setText("MOVIES");
        jButtonMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoviesActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        North.setBackground(new java.awt.Color(175, 52, 59));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        jButtonHome1.setBackground(new java.awt.Color(175, 52, 59));
        jButtonHome1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonHome1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHome1.setText("HOME");
        jButtonHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHome1ActionPerformed(evt);
            }
        });

        jButtonMovies1.setBackground(new java.awt.Color(175, 52, 59));
        jButtonMovies1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonMovies1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMovies1.setText("MOVIES");
        jButtonMovies1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMovies1ActionPerformed(evt);
            }
        });

        jButtonReservation1.setBackground(new java.awt.Color(175, 52, 59));
        jButtonReservation1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonReservation1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReservation1.setText("RESERVATION");
        jButtonReservation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservation1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NorthLayout = new javax.swing.GroupLayout(North);
        North.setLayout(NorthLayout);
        NorthLayout.setHorizontalGroup(
            NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NorthLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(jButtonHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMovies1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonReservation1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        NorthLayout.setVerticalGroup(
            NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NorthLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addGroup(NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NorthLayout.createSequentialGroup()
                        .addGroup(NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMovies1)
                            .addComponent(jButtonReservation1)
                            .addComponent(jButtonHome1))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NorthLayout.createSequentialGroup()
                        .addComponent(logo)
                        .addContainerGap())))
        );

        getContentPane().add(North, java.awt.BorderLayout.NORTH);

        Center.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitleofMovie.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitleofMovie.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabelTitleofMovie.setForeground(new java.awt.Color(175, 52, 59));
        jLabelTitleofMovie.setText("TITLE OF MOVIE");

        Time10Button.setBackground(new java.awt.Color(242, 198, 112));
        HourSelectBtnGroup.add(Time10Button);
        Time10Button.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Time10Button.setForeground(new java.awt.Color(255, 255, 255));
        Time10Button.setText("10:00AM");
        Time10Button.setEnabled(false);
        Time10Button.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MovieSelectStateChanged(evt);
            }
        });

        Time12Button.setBackground(new java.awt.Color(242, 198, 112));
        HourSelectBtnGroup.add(Time12Button);
        Time12Button.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Time12Button.setForeground(new java.awt.Color(255, 255, 255));
        Time12Button.setText("12:30PM");
        Time12Button.setEnabled(false);
        Time12Button.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MovieSelectStateChanged(evt);
            }
        });

        Time3Button.setBackground(new java.awt.Color(242, 198, 112));
        HourSelectBtnGroup.add(Time3Button);
        Time3Button.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Time3Button.setForeground(new java.awt.Color(255, 255, 255));
        Time3Button.setText("3:00PM");
        Time3Button.setEnabled(false);
        Time3Button.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MovieSelectStateChanged(evt);
            }
        });

        Time6Button.setBackground(new java.awt.Color(242, 198, 112));
        HourSelectBtnGroup.add(Time6Button);
        Time6Button.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Time6Button.setForeground(new java.awt.Color(255, 255, 255));
        Time6Button.setText("6:00PM");
        Time6Button.setEnabled(false);
        Time6Button.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MovieSelectStateChanged(evt);
            }
        });

        panel3.setBackground(new java.awt.Color(175, 52, 59));
        panel3.setForeground(new java.awt.Color(175, 52, 59));

        Home3.setBackground(new java.awt.Color(255, 255, 255));
        Home3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Home3.setForeground(new java.awt.Color(242, 198, 112));
        Home3.setText("Personal Information");

        Home6.setBackground(new java.awt.Color(255, 255, 255));
        Home6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Home6.setForeground(new java.awt.Color(255, 255, 255));
        Home6.setText("Name:");

        Home7.setBackground(new java.awt.Color(255, 255, 255));
        Home7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Home7.setForeground(new java.awt.Color(255, 255, 255));
        Home7.setText("Email:");

        jTextFieldName.setBackground(new java.awt.Color(242, 198, 112));
        jTextFieldName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextFieldName.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNameKeyPressed(evt);
            }
        });

        jTextFieldEmail.setBackground(new java.awt.Color(242, 198, 112));
        jTextFieldEmail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Home3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Home6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Home7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(jTextFieldEmail))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(Home3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Home6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Home7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        panel5.setBackground(new java.awt.Color(242, 198, 112));

        Home8.setBackground(new java.awt.Color(255, 255, 255));
        Home8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Home8.setForeground(new java.awt.Color(175, 52, 59));
        Home8.setText("Number of Tickers");

        Home10.setBackground(new java.awt.Color(255, 255, 255));
        Home10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Home10.setForeground(new java.awt.Color(255, 255, 255));
        Home10.setText("Cost:");

        jLabelTicketsTotal.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTicketsTotal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabelTicketsTotal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTicketsTotal.setText("440.00");

        Home13.setBackground(new java.awt.Color(255, 255, 255));
        Home13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Home13.setForeground(new java.awt.Color(255, 255, 255));
        Home13.setText("Quantity:");

        Home14.setBackground(new java.awt.Color(255, 255, 255));
        Home14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Home14.setForeground(new java.awt.Color(255, 255, 255));
        Home14.setText("Sub Total:");

        jButtonMore.setBackground(new java.awt.Color(175, 52, 59));
        jButtonMore.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMore.setForeground(new java.awt.Color(242, 198, 112));
        jButtonMore.setText("+");
        jButtonMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoreActionPerformed(evt);
            }
        });

        jButtonLess.setBackground(new java.awt.Color(175, 52, 59));
        jButtonLess.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLess.setForeground(new java.awt.Color(242, 198, 112));
        jButtonLess.setText("-");
        jButtonLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLessActionPerformed(evt);
            }
        });

        Home15.setBackground(new java.awt.Color(255, 255, 255));
        Home15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Home15.setForeground(new java.awt.Color(255, 255, 255));
        Home15.setText("440.00");

        jLabelTicketQuantity.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTicketQuantity.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabelTicketQuantity.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTicketQuantity.setText("1");

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addComponent(Home8, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel5Layout.createSequentialGroup()
                        .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Home10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Home15, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel5Layout.createSequentialGroup()
                                .addComponent(Home13, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(Home14, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                            .addGroup(panel5Layout.createSequentialGroup()
                                .addComponent(jButtonLess)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelTicketQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonMore)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelTicketsTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Home8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Home10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Home13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Home14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTicketsTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMore)
                    .addComponent(jButtonLess)
                    .addComponent(jLabelTicketQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Home15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        panel4.setBackground(new java.awt.Color(175, 52, 59));
        panel4.setForeground(new java.awt.Color(175, 52, 59));

        Home5.setBackground(new java.awt.Color(255, 255, 255));
        Home5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Home5.setForeground(new java.awt.Color(242, 198, 112));
        Home5.setText("Snack Bar");

        Home11.setBackground(new java.awt.Color(255, 255, 255));
        Home11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Home11.setForeground(new java.awt.Color(255, 255, 255));
        Home11.setText("Sub Total:");

        jTextFieldSnackTotal.setBackground(new java.awt.Color(242, 198, 112));
        jTextFieldSnackTotal.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextFieldSnackTotal.setForeground(new java.awt.Color(175, 52, 59));
        jTextFieldSnackTotal.setDisabledTextColor(new java.awt.Color(175, 52, 59));
        jTextFieldSnackTotal.setEnabled(false);
        jTextFieldSnackTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSnackTotalActionPerformed(evt);
            }
        });

        OGPopSpinner.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        OGPopSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        OGPopSpinner.setBorder(null);
        OGPopSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                OrderChange(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Original Popcorn (P50.00)");

        CheePopSpinner.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        CheePopSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        CheePopSpinner.setBorder(null);
        CheePopSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                OrderChange(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cheese Popcorn (P55.00)");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BBQ Popcorn (P55.00)");

        BBQPopSpinner.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        BBQPopSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        BBQPopSpinner.setBorder(null);
        BBQPopSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                OrderChange(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nachos (P60.00)");

        NachoSpinner.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        NachoSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        NachoSpinner.setBorder(null);
        NachoSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                OrderChange(evt);
            }
        });

        SodaSpinner.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        SodaSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SodaSpinner.setToolTipText("");
        SodaSpinner.setBorder(null);
        SodaSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                OrderChange(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Soda (P30.00)");

        WaterSpinner.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        WaterSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        WaterSpinner.setToolTipText("");
        WaterSpinner.setBorder(null);
        WaterSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                OrderChange(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Water (P25.00)");

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Home5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(OGPopSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(CheePopSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(BBQPopSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(NachoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(SodaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(WaterSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Home11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldSnackTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Home5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OGPopSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheePopSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BBQPopSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NachoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SodaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WaterSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(49, 49, 49)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Home11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSnackTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        panel6.setBackground(new java.awt.Color(242, 198, 112));

        Home9.setBackground(new java.awt.Color(255, 255, 255));
        Home9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Home9.setForeground(new java.awt.Color(175, 52, 59));
        Home9.setText("Total Bill");

        jLabelTotalBill.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTotalBill.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelTotalBill.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalBill.setText("00.00");

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Home9, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Home9)
                    .addComponent(jLabelTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButtonCancel.setBackground(new java.awt.Color(242, 198, 112));
        jButtonCancel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setText("CANCEL");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonConfirm.setBackground(new java.awt.Color(242, 198, 112));
        jButtonConfirm.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonConfirm.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConfirm.setText("CONFIRM");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        MovieSelectComboBox.setBackground(new java.awt.Color(242, 198, 112));
        MovieSelectComboBox.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        MovieSelectComboBox.setForeground(new java.awt.Color(175, 52, 59));
        MovieSelectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select a Movie and Time", "Flow (March, 12)", "The Gorge (March, 12)", "The Dead Thing (March, 12)", "Moana Returns (March, 12)", "The Companion (March, 12)", "The Complete Unknown (March, 12)" }));
        MovieSelectComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MovieSelectStateChanged(evt);
            }
        });

        javax.swing.GroupLayout CenterLayout = new javax.swing.GroupLayout(Center);
        Center.setLayout(CenterLayout);
        CenterLayout.setHorizontalGroup(
            CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CenterLayout.createSequentialGroup()
                        .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CenterLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Time10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Time12Button, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Time3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Time6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MovieSelectComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CenterLayout.createSequentialGroup()
                                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(CenterLayout.createSequentialGroup()
                        .addComponent(jLabelTitleofMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        CenterLayout.setVerticalGroup(
            CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitleofMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CenterLayout.createSequentialGroup()
                        .addComponent(MovieSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Time10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Time12Button, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Time3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Time6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CenterLayout.createSequentialGroup()
                        .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(Center, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TO DO
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservationActionPerformed
        // reservation button from menu
        ReservationPage Reservation = new ReservationPage();
        Reservation.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonReservationActionPerformed

    private void jButtonMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoviesActionPerformed
        // movie button from menu
        MoviesPage Movies = new MoviesPage();
        Movies.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_jButtonMoviesActionPerformed

    private void jButtonHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHome1ActionPerformed
        // movie button from menu
        HomePage Home = new HomePage();
        Home.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_jButtonHome1ActionPerformed

    private void jButtonReservation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservation1ActionPerformed
        // reservation button from menu
        ReservationPage Reservation = new ReservationPage();
        Reservation.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonReservation1ActionPerformed

    private void jButtonMovies1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMovies1ActionPerformed
        // movie button from menu
        MoviesPage Movies = new MoviesPage();
        Movies.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonMovies1ActionPerformed

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void resetReservation() {
        ticketNum = 1;
        jLabelTicketQuantity.setText("1");
        jLabelTicketsTotal.setText("440.00");

        OGPopSpinner.setValue(0);
        CheePopSpinner.setValue(0);
        BBQPopSpinner.setValue(0);
        NachoSpinner.setValue(0);
        SodaSpinner.setValue(0);
        WaterSpinner.setValue(0);
        jTextFieldSnackTotal.setText("Php 0");

        jLabelTotalBill.setText("Php 440.00");

        jTextFieldName.setText("");
        jTextFieldEmail.setText("");

        MovieSelectComboBox.setSelectedIndex(0);
        Time10Button.setEnabled(false);
        Time12Button.setEnabled(false);
        Time3Button.setEnabled(false);
        Time6Button.setEnabled(false);
        Time10Button.setSelected(false);
        Time12Button.setSelected(false);
        Time3Button.setSelected(false);
        Time6Button.setSelected(false);
    }
    
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        int confirmCancel = JOptionPane.showConfirmDialog(this,
                "Cancel reservation?",
                "Confirm Cancellation",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirmCancel == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Reservation Cancelled!");
            
            // option for user if they want to go back browsing to movies page
            int continueBrowsing = JOptionPane.showConfirmDialog(this,
                    "Want to continue browsing?",
                    "Continue Browsing?",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (continueBrowsing == JOptionPane.YES_OPTION) {
                MoviesPage movies = new MoviesPage();
                movies.setVisible(true);
                this.dispose();
                resetReservation();
            } else {
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButtonCancelActionPerformed
    // NAME AND EMAIL TEXTFIELD
    private void jTextFieldNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameKeyPressed
        char keyChar = evt.getKeyChar();
        int keyCode = evt.getKeyCode();
        
        if ((keyChar >= 'A' && keyChar <= 'Z') || (keyChar >= 'a' && keyChar <= 'z')) { // allow letters
            jTextFieldName.setEditable(true);
        }
        else if (keyCode == KeyEvent.VK_BACK_SPACE || keyCode == KeyEvent.VK_DELETE || keyCode == KeyEvent.VK_SPACE || keyCode == KeyEvent.VK_SHIFT || keyCode == KeyEvent.VK_CAPS_LOCK){ // allowed actions
            jTextFieldName.setEditable(true);
        }
        else if (keyCode == KeyEvent.VK_ENTER){ // code to run after pressing enter
            // character limit
            String jTFInput = jTextFieldName.getText();
            int jTFInputLength = jTFInput.length();
            if (jTFInputLength > 12){
                JOptionPane.showMessageDialog(this, "Please input up to 12 characters only.");
            }
            // insert other enter functions here
        }
        else
        {
            jTextFieldName.setEditable(false);
            JOptionPane.showMessageDialog(this, "Invalid input. Please only enter letters.");  
        }
    }//GEN-LAST:event_jTextFieldNameKeyPressed

    private void jTextFieldEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyPressed
       char keyChar = evt.getKeyChar();
        int keyCode = evt.getKeyCode();
        
        if (Character.isLetterOrDigit(keyChar) || keyChar == '@' || keyChar == '.') { // allow letters, numbers, @, and .
            jTextFieldName.setEditable(true);
        }
        else if (keyCode == KeyEvent.VK_BACK_SPACE || keyCode == KeyEvent.VK_DELETE || keyCode == KeyEvent.VK_SPACE || keyCode == KeyEvent.VK_SHIFT || keyCode == KeyEvent.VK_CAPS_LOCK){ // allowed actions
            jTextFieldName.setEditable(true);
        }
        else if (keyCode == KeyEvent.VK_ENTER){ // code to run after pressing enter
            // insert other enter functions here
        }
        else
        {
            jTextFieldName.setEditable(false);
            JOptionPane.showMessageDialog(this, "Invalid input. Only letters, @, and . are allowed.");  
        }
    }//GEN-LAST:event_jTextFieldEmailKeyPressed
    // METHOD FOR UPDATING TOTAL BILL
    private void updateTotalBill() {
        try {
            double ticketTotal = Double.parseDouble(jLabelTicketsTotal.getText());
            double snackTotal = Double.parseDouble(jTextFieldSnackTotal.getText().replace("Php  ", "").trim());
            double totalBill = ticketTotal + snackTotal;
        
            jLabelTotalBill.setText("Php " + df.format(totalBill));
        } catch (NumberFormatException e) {
            jLabelTotalBill.setText("Php 0.00");
        }
    }    

    // TICKET JBUTTON
    private void jButtonLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLessActionPerformed
        if (ticketNum == 1){
            JOptionPane.showMessageDialog(this, "Ticket quantity cannot be zero.");
        }
        else{
            ticketNum--;
            jLabelTicketQuantity.setText(Integer.toString(ticketNum));
            
            ticketSubtotal = ticketNum * 440;
            String ticketSubtotalString = df.format(ticketSubtotal);
            jLabelTicketsTotal.setText(ticketSubtotalString);
            updateTotalBill(); // method for updating the total bill
        }
    }//GEN-LAST:event_jButtonLessActionPerformed

    private void jButtonMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoreActionPerformed
        if (ticketNum == 10){
            JOptionPane.showMessageDialog(this, "Sorry! You cannot order more than 10 tickets.");
        }
        else{
            ticketNum++;
            jLabelTicketQuantity.setText(Integer.toString(ticketNum));
            
            ticketSubtotal = ticketNum * 440;
            String ticketSubtotalString = df.format(ticketSubtotal);
            jLabelTicketsTotal.setText(ticketSubtotalString);
            updateTotalBill(); // method for updating the total bill
        }
    }//GEN-LAST:event_jButtonMoreActionPerformed

    private void OrderChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_OrderChange
        int Subtotal = (Integer) OGPopSpinner.getValue() * 50
                + (Integer) CheePopSpinner.getValue() * 55
                + (Integer) BBQPopSpinner.getValue() * 55
                + (Integer) NachoSpinner.getValue() * 60
                + (Integer) SodaSpinner.getValue() * 30 
                + (Integer) WaterSpinner.getValue() * 25;
        
        // can also add the + ticket here and dupe, or append to outside method
        
        jTextFieldSnackTotal.setText("Php  " + Subtotal);
        updateTotalBill(); // method for updating the total bill
    }//GEN-LAST:event_OrderChange

    private void MovieSelectStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MovieSelectStateChanged
        jLabelTitleofMovie.setText(String.valueOf(MovieSelectComboBox.getSelectedItem())); 
        //Added this part above ^^^ so that the "title of the movie" jlabel will be updated or change when a movie is selected
        
        Time10Button.setEnabled(false);
        Time12Button.setEnabled(false);
        Time3Button.setEnabled(false);
        Time6Button.setEnabled(false);
            //Initializes all to disabled (also to reset when on first option)
        
        switch (String.valueOf(MovieSelectComboBox.getSelectedItem())){ //converts object to string
            case "Flow (March, 12)": 
                Time10Button.setEnabled(true); //enables options
                Time12Button.setEnabled(true);
                Time3Button.setEnabled(true);
                if (Time6Button.isSelected()) Time6Button.setSelected(false); //unselects if previously selected
                Time6Button.setEnabled(false); //Disables 6 PM
            case "The Gorge (March, 12)": 
                Time10Button.setEnabled(true);
                Time12Button.setEnabled(true);
                if (Time3Button.isSelected()) Time3Button.setSelected(false);
                if (Time6Button.isSelected()) Time6Button.setSelected(false);
                Time3Button.setEnabled(false);
                Time6Button.setEnabled(false);
                break;
            
            case "The Dead Thing (March, 12)": 
                Time10Button.setEnabled(true);
                Time12Button.setEnabled(true);
                if (Time3Button.isSelected()) Time3Button.setSelected(false);
                if (Time6Button.isSelected()) Time6Button.setSelected(false);
                Time3Button.setEnabled(false);
                Time6Button.setEnabled(false);
                break;
                
            case "Moana Returns (March, 12)": 
                Time10Button.setEnabled(true);
                Time12Button.setEnabled(true);
                Time3Button.setEnabled(true);
                if (Time6Button.isSelected()) Time6Button.setSelected(false);
                Time6Button.setEnabled(false);
                break;
                
            case "The Companion (March, 12)" : 
                Time3Button.setEnabled(true);
                Time6Button.setEnabled(true);
                if (Time10Button.isSelected()) Time10Button.setSelected(false);
                if (Time12Button.isSelected()) Time12Button.setSelected(false);
                Time10Button.setEnabled(false);
                Time12Button.setEnabled(false);
                break;
                
            case "The Complete Unknown (March, 12)" : 
                Time3Button.setEnabled(true);
                Time6Button.setEnabled(true);
                if (Time10Button.isSelected()) Time10Button.setSelected(false);
                if (Time12Button.isSelected()) Time12Button.setSelected(false);
                Time10Button.setEnabled(false);
                Time12Button.setEnabled(false);
                break;
        }
    }//GEN-LAST:event_MovieSelectStateChanged

    private void jTextFieldSnackTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSnackTotalActionPerformed
        jTextFieldSnackTotal.setEditable(false); // so user cant type on it
    }//GEN-LAST:event_jTextFieldSnackTotalActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner BBQPopSpinner;
    private javax.swing.JPanel Center;
    private javax.swing.JSpinner CheePopSpinner;
    private javax.swing.JLabel Home10;
    private javax.swing.JLabel Home11;
    private javax.swing.JLabel Home13;
    private javax.swing.JLabel Home14;
    private javax.swing.JLabel Home15;
    private javax.swing.JLabel Home3;
    private javax.swing.JLabel Home5;
    private javax.swing.JLabel Home6;
    private javax.swing.JLabel Home7;
    private javax.swing.JLabel Home8;
    private javax.swing.JLabel Home9;
    private javax.swing.ButtonGroup HourSelectBtnGroup;
    private javax.swing.JComboBox<String> MovieSelectComboBox;
    private javax.swing.JSpinner NachoSpinner;
    private javax.swing.JPanel North;
    private javax.swing.JSpinner OGPopSpinner;
    private javax.swing.JSpinner SodaSpinner;
    private javax.swing.JToggleButton Time10Button;
    private javax.swing.JToggleButton Time12Button;
    private javax.swing.JToggleButton Time3Button;
    private javax.swing.JToggleButton Time6Button;
    private javax.swing.JSpinner WaterSpinner;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonHome1;
    private javax.swing.JButton jButtonLess;
    private javax.swing.JButton jButtonMore;
    private javax.swing.JButton jButtonMovies;
    private javax.swing.JButton jButtonMovies1;
    private javax.swing.JButton jButtonReservation;
    private javax.swing.JButton jButtonReservation1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelTicketQuantity;
    private javax.swing.JLabel jLabelTicketsTotal;
    private javax.swing.JLabel jLabelTitleofMovie;
    private javax.swing.JLabel jLabelTotalBill;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldSnackTotal;
    private javax.swing.JLabel logo;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    private java.awt.Panel panel6;
    // End of variables declaration//GEN-END:variables
}
